# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2016/11/30/setting-up-gitlab-ci-for-android-projects/, by Greyson Parrelli
image: saeftaher/react-native-app-builder

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "24.0.0"
  ANDROID_SDK_TOOLS: "24.4.1"
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - android/.bundler
  - .gradle/wrapper
  - .gradle/caches
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x android/gradlew
  
stages:
  - release

internal_release:
  stage: release
  script:
    - npm install
    - react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
    - cd android
    - echo $API_KEY >> apiKey.json
    - bundle install --path=./.bundler
    - fastlane beta
  artifacts:
    paths:
    - app/build/outputs/


